// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qszgrpkaszsoezuvulfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzemdycGthc3pzb2V6dXZ1bGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNDc5MTMsImV4cCI6MjA1MjkyMzkxM30.4Gvj0D8twTd9OkAEtuRKH5Msz3208b9zNaFX34iUyFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);